services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: app_db
      MARIADB_USER: fullstack_user
      MARIADB_PASSWORD: fullstack_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/src/config/init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" 
      - "9001:9001"   
    volumes:
      - minio_data:/data

  #backend:
  #  build: ./backend
  #  container_name: backend
  #  restart: always
  #  command: npm start
  #  depends_on:
  #    - db
  #    - minio
  #  ports:
  #    - "3000:3000"
  #  volumes:
  #    - ./backend:/app
  #  environment:
  #    DB_HOST: db
  #    DB_USER: fullstack_user
  #    DB_PASSWORD: fullstack_pass
  #    DB_NAME: app_db
#
  #    MINIO_ENDPOINT: minio
  #    MINIO_PORT: 9000
  #    MINIO_USE_SSL: "false"
  #    MINIO_ACCESS_KEY: minioadmin
  #    MINIO_SECRET_KEY: minioadmin

volumes:
  db_data:
  minio_data:
